appdata:  
    build: ./docker-app-data/
    volumes: 
     - /srv/www:/srv/www:rw
mysql:
    build: ./docker-mysql/
    environment:
      - MYSQL_DATABASE=myappdb
      - MYSQL_ROOT_PASSWORD=1234
    volumes_from:
      - appdata
phpfpm:
    build: ./docker-phpfpm/
    volumes_from:
      - appdata
    links:
      - mysql
    privileged: true
nginx:
    build: ./docker-nginx/
    volumes_from:
      - appdata
    links:
      - phpfpm
    ports:
      - 80:80
    privileged: true

