app-data:  
    container_name: app-data
    build: ./docker-app-data/
    volumes: 
     - /srv/www:/srv/www:rw
mysql:
    container_name: mysql
    build: ./docker-mysql/
    environment:
      - MYSQL_DATABASE=myappdb
      - MYSQL_ROOT_PASSWORD=1234
    volumes_from:
      - app-data
phpfpm:
    container_name: phpfpm
    build: ./docker-phpfpm/
    volumes_from:
      - app-data
    links:
      - mysql:mysql
    privileged: true
nginx:
    container_name: nginx
    build: ./docker-nginx/
    volumes_from:
      - app-data
    links:
      - phpfpm:fpm
    ports:
      - 80:80
    privileged: true



