appdata:  
    build: ./docker-app-data/
    volumes: 
     - ~/workspace:/srv/www:rw
     - ~/.docker/data/redis:/srv/redis:rw
     - ~/.docker/data/db:/var/lib/mysql:rw
redis:
    image: redis
mysql:
    build: ./docker-mysql/
    environment:
      - MYSQL_DATABASE=myappdb
      - MYSQL_ROOT_PASSWORD=1234
    volumes_from:
      - appdata
phpfpm:
    build: ./docker-phpfpm/
    volumes_from:
      - appdata
      - redis
    links:
      - mysql
    privileged: true
nginx:
    build: ./docker-nginx/
    volumes_from:
      - appdata
    links:
      - phpfpm
    ports:
      - 8000:80
    privileged: true

