appdata:  
    image: jorelcb/app-data
    volumes: 
     - ~/.docker/data/www:/srv/www:rw
     - ~/.docker/data/redis:/srv/redis:rw
     - ~/.docker/data/db:/var/lib/mysql:rw
redis:
    image: redis
mysql:
    image: jorelcb/mysql
    environment:
      - MYSQL_DATABASE=myappdb
      - MYSQL_ROOT_PASSWORD=1234
    volumes_from:
      - appdata
phpfpm:
    image: jorelcb/phpfpm
    volumes_from:
      - appdata
    links:
      - mysql
      - redis
    privileged: true
nginx:
    image: jorelcb/nginx
    volumes_from:
      - appdata
    links:
      - phpfpm
    ports:
      - 8000:80
    privileged: true

